import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";
import type { PdfParty } from "./billing-document";

/** Payment receipt PDF (spec §12 "Generate payment receipt."). */

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica", color: "#111827" },
  headerRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 24 },
  businessName: { fontSize: 14, fontWeight: 700, marginBottom: 4 },
  muted: { color: "#6b7280" },
  title: { fontSize: 16, fontWeight: 700, textAlign: "right" },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 5, borderBottomWidth: 1, borderBottomColor: "#e5e7eb" },
  label: { color: "#6b7280" },
  amountBlock: { marginTop: 16, alignItems: "flex-end" },
  amountLabel: { fontSize: 9, color: "#6b7280", textTransform: "uppercase" },
  amountValue: { fontSize: 20, fontWeight: 700, marginTop: 2 },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, fontSize: 8, color: "#9ca3af", textAlign: "center" },
});

export function ReceiptPdf({
  business,
  customer,
  receiptId,
  paymentDate,
  method,
  referenceId,
  invoiceNumber,
  amount,
  currency,
  balanceAfter,
}: {
  business: PdfParty;
  customer: PdfParty;
  receiptId: string;
  paymentDate: string;
  method: string;
  referenceId?: string | null;
  invoiceNumber: string;
  amount: string;
  currency: string;
  balanceAfter: string;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerRow}>
          <View>
            <Text style={styles.businessName}>{business.name}</Text>
            {business.addressLines.map((line, i) => (
              <Text key={i} style={styles.muted}>{line}</Text>
            ))}
            {business.gstin ? <Text style={styles.muted}>GSTIN: {business.gstin}</Text> : null}
          </View>
          <View>
            <Text style={styles.title}>PAYMENT RECEIPT</Text>
            <Text style={[styles.muted, { textAlign: "right", marginTop: 4 }]}>#{receiptId}</Text>
          </View>
        </View>

        <Text style={{ marginBottom: 4, fontWeight: 700 }}>Received from</Text>
        <Text>{customer.name}</Text>
        {customer.addressLines.map((line, i) => (
          <Text key={i} style={styles.muted}>{line}</Text>
        ))}

        <View style={{ marginTop: 20 }}>
          <View style={styles.row}>
            <Text style={styles.label}>Invoice</Text>
            <Text>{invoiceNumber}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Payment date</Text>
            <Text>{paymentDate}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Method</Text>
            <Text>{method}</Text>
          </View>
          {referenceId ? (
            <View style={styles.row}>
              <Text style={styles.label}>Reference</Text>
              <Text>{referenceId}</Text>
            </View>
          ) : null}
          <View style={styles.row}>
            <Text style={styles.label}>Remaining balance on invoice</Text>
            <Text>{currency} {balanceAfter}</Text>
          </View>
        </View>

        <View style={styles.amountBlock}>
          <Text style={styles.amountLabel}>Amount received</Text>
          <Text style={styles.amountValue}>{currency} {amount}</Text>
        </View>

        <Text style={styles.footer}>Generated by Dotnapps Invoice</Text>
      </Page>
    </Document>
  );
}
